# Generated by Django 2.1.7 on 2019-03-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='password',
            new_name='lvl',
        ),
    ]
